baseURL = "https://obicho.github.io/"
languageCode = "en-us"
title = "Cho-Nan Tsai CTO media interviews, essays and talks"
theme = "ng"
sectionPagesMenu = "main"
buildFuture = true
googleAnalytics = 'G-R0SH0MD853'

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
   tag = "tags"
   category = "categories"